[package]
authors = ["Rahix <rahix@rahix.de>"]
name = "arduino-leonardo"
version = "0.1.0"

[features]
docs = ["atmega32u4-hal/docs"]

[dependencies]
atmega32u4 = "0.1.3"
# atmega32u4 = { path="../atmega32u4" }

[dependencies.atmega32u4-hal]
optional = false
path = "../atmega32u4-hal"
